version: '3'

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      # - ../wedding-website/conf/1_domain.cn_bundle.crt:/etc/nginx/1_domain.cn_bundle.crt
      # - ../wedding-website/conf/2_domain.cn.key:/etc/nginx/2_domain.cn.key
      - ../wedding-website/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../wedding-website/dist:/usr/share/nginx/wwwroot
  backend:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - 3001:3001
    depends_on:
      - db
  db:
    image: postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2300
      - APP_DB_NAME=wedding
